#!/bin/bash

set -e

LIBMCRYPT_VERSION="2.5.8"

basedir="$( cd -P "$( dirname "$0" )" && pwd )"

# make a temp directory
tempdir="$( mktemp -t libmcrypt_XXXX )"
rm -rf $tempdir
mkdir -p $tempdir

pushd $tempdir

# download and extract libmcrypt
curl -L "http://downloads.sourceforge.net/project/mcrypt/Libmcrypt/${LIBMCRYPT_VERSION}/libmcrypt-${LIBMCRYPT_VERSION}.tar.gz?r=&ts=1364878418&use_mirror=switch" -o - | tar zx

# build and package libmcrypt for heroku
vulcan build -v -s libmcrypt-$LIBMCRYPT_VERSION -o $tempdir/libmcrypt-heroku-bin.tar.gz -p /app/local -c './configure --prefix=/app/local --disable-rpath && make && make install' 

popd

cp $tempdir/libmcrypt-heroku-bin.tar.gz .

echo "+ Binaries available at ./libmcrypt-heroku-bin.tar.gz"
echo "+ Upload this package to Amazon S3."
